### ISSUE TITLE
Gibberish when setting ESteps

### ISSUE THREAD

**Issue by tjwitman** [JGMaker3dofficial/artistd#35] opened 2021-03-06 16:44 UTC
### Bug Description

<After flashing firmware and begin setting ESteps, I select ESteps for E1 or E2, I see gibberish where the numbers are supposed to be>

### My Configurations

My zip files would be exactly what is on this page to go along with the robin.pro file

### Steps to Reproduce

<go to the Advanced page, scroll down to ESteps and select E1 or E2>

**Expected behavior:** I would expect to see the number of steps

**Actual behavior:** I actually see the familiar gibberish
![IMG_20210306_113326](https://user-images.githubusercontent.com/21091959/110214150-58bb3480-7e71-11eb-9083-98bb5a8c7ccf.jpg)

#### Additional Information

* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by mikejr83** [comment] 2021-03-07 00:09
Looks like it's trying to display too much on the single line.

What version are you on? Just double checking to see if you're on the recently released 2.0.6 version.

**Comment by tjwitman** [comment] 2021-03-07 00:28
It's Mark's Beta that he just put up.  2021.3-beta

**Comment by tjwitman** [comment] 2021-03-07 00:31
Damn, didn't want to close it!

**Comment by tjwitman** [comment] 2021-03-07 00:36
reopened

**Comment by bodinjm** [comment] 2021-03-07 20:19
It does the same for me even in french

**Comment by nlnpereira** [comment] 2021-03-08 16:03
Same gibberish issue on E-Step configuration screen with mine.

**Comment by inspectionsbybob** [comment] 2021-03-10 01:25
Same Gibberish on 2021.3.0.6.

**Comment by mikejr83** [comment] 2021-03-10 20:08
Confirmed fixed in [v2021.4-beta ](https://github.com/JGMaker3dofficial/artistd/releases/tag/v2021.4-beta)

**Closed by mikejr83** 2021-03-10 20:08 UTC
